spring:
  datasource:
    username: root
    url: jdbc:mysql://${DATABASE_URL:localhost}/feel_dev?createDatabaseIfNotExist=true
    driver-class-name: org.gjt.mm.mysql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    encoding: UTF-8