spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost/feel_dev?createDatabaseIfNotExist=true
    driver-class-name: org.gjt.mm.mysql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
    
server:
  port: 8080    
  host-name: localhost   

---
spring:
  profiles: production
  datasource:  
    username: root  
    password: 5cf7de5eef05d0b3aae6b11f25bdb18cb54067fcbe05c288
    url: jdbc:mysql://localhost/feel_prod?createDatabaseIfNotExist=true
    driver-class-name: org.gjt.mm.mysql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false     
  flyway:
    encoding: UTF-8
    enabled: false
  devtools:
    livereload:
      enabled: false
 
      
server:
  port: 80
  host-name: people.caelum.com.br          
