spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost/feel_dev?createDatabaseIfNotExist=true
    driver-class-name: org.gjt.mm.mysql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
    
server:
  port: 8080       

---
spring:
  profiles: production
  datasource:    
    url: jdbc:mysql://adffdadf2341:adf4234@us-cdbr-east.cleardb.com/heroku_db?reconnect=true&createDatabaseIfNotExist=true
    driver-class-name: org.gjt.mm.mysql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    encoding: UTF-8
  devtools:
    livereload:
      enabled: false
      
server:
  port: ${PORT}          
